name: CI build pack
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build zip
        run: |
          cd files_to_zip; zip -r ../build/vendor.zip *; cd ..

      - name: Publish
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files: build/vendor.zip
          name: Publish Action
          email: my.github@email.com 
