name: CI build pack
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # get repo
      - uses: actions/upload-artifact@master  # upload the whole thing as a zip without subfolders
        with:
          name: vendor
          path: files_to_zip
